[tox]
envlist = py39,py310,py311,py312,py313,py314,py27
skipsdist = False

[testenv]
basepython =
    py39: python3.9
    py310: python3.10
    py311: python3.11
    py312: python3.12
    py313: python3.13
    py314: python3.14
    py27: python2.7
setenv =
    PIP_DISABLE_PIP_VERSION_CHECK = 1
commands =
    python -m unittest discover -s test -p 'test_*.py'
